name: Add New Recipe
description: Add a new recipe to the collection
title: "Add Recipe: "
labels: ["recipe-add"]
body:
  - type: markdown
    attributes:
      value: |
        Fill out the form below to add a new recipe to your collection.
        
        **Note:** This will automatically create a pull request that updates the recipes.json file. The source website will be automatically detected from the URL.
  
  - type: input
    id: title
    attributes:
      label: Recipe Title
      description: The name of the recipe
      placeholder: "e.g., Chocolate Chip Cookies"
    validations:
      required: true
  
  - type: input
    id: url
    attributes:
      label: Recipe URL
      description: The URL where you found this recipe
      placeholder: "https://example.com/recipe"
    validations:
      required: true
  
  - type: dropdown
    id: tags
    attributes:
      label: Recipe Tags
      description: Select all applicable tags (hold Ctrl/Cmd to select multiple)
      multiple: true
      options:
        - breakfast
        - main-dishes
        - sides
        - soups
        - desserts
        - breads
        - favorites
        - quick
        - vegetarian
        - vegan
        - gluten-free
        - dairy-free
    validations:
      required: true
  
  - type: input
    id: custom_tags
    attributes:
      label: Custom Tags (optional)
      description: Add any additional tags not in the list above, separated by commas
      placeholder: "italian, pasta, comfort-food"
  
  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      description: Any additional notes or modifications you made to the recipe
      placeholder: "I doubled the chocolate chips and used dark chocolate instead of milk chocolate" 